name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_c:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make C
        run: |
          cd c
          make

      - name: Test C
        run: |
          cd c
          make
          make test

      - name: Clean C
        run: |
          cd c
          make
          make clean
  build_cpp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make C++
        run: |
          cd cpp
          make

      - name: Test C++
        run: |
          cd cpp
          make
          make test

      - name: Clean C++
        run: |
          cd cpp
          make
          make clean