name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Make C
      run: |
        cd c
        make
        
    - name: Make C++
      run: |
        cd cpp
        make
